---
repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v2.3.0
   hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
 - repo: https://github.com/pre-commit/mirrors-mypy
   rev: 'v0.940'
   hooks:
    - id: mypy
      additional_dependencies: [tokenize-rt==3.2.0]
 - repo: https://github.com/adrienverge/yamllint
   rev: 'v1.26.3'
   hooks:
    - id: yamllint
      name: yamllint
      entry: yamllint
      language: python
      types: [yaml]
 - repo: https://github.com/astral-sh/ruff-pre-commit
   # Ruff version.
   rev: v0.1.14
   hooks:
    # Run the linter.
    - id: ruff
      types_or: [python, pyi, jupyter]
      args: [--fix]
    # Run the formatter.
    - id: ruff-format
      types_or: [python, pyi, jupyter]
