[tool.poetry]
name = "pyalanysis"
version = "0.1.3-alpha.0"
description = "A package to analyse and visualize artificial light at night (ALAN)"
authors = ["Anton Bossenbroek <anton.bossenbroek@gmail.com>"]
license = "BSD-3"
readme = "README.md"
homepage = "https://github.com/pyalanysis/pyalanysis"
repository = "https://github.com/pyalanysis/pyalanysis"
packages = [ {include = "src/**/*.py"} ]

[tool.poetry.dependencies]
python = "^3.9"
MechanicalSoup = "^1.1.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
flake8 = "^4.0.1"
mypy = "^0.940"
coverage = {extras = ["toml"], version = "^6.3.2"}
pytest-cov = "^3.0.0"
myst-parser = "^0.17.0"
black = "^22.1.0"
flake8-bandit = "^3.0.0"
flake8-black = "^0.3.2"
flake8-bugbear = "^22.1.11"
flake8-import-order = "^0.18.1"
safety = "^1.10.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.paths]
source = ["src", "*/site-packages"]

[tool.coverage.run]
branch = true
source = ["src"]

[tool.coverage.report]
show_missing = true
fail_under = 100
