---
name: pyalanysis_demo_env
channels:
  - conda-forge
dependencies:
  - python=3.8
  - rioxarray~=0.10
  - pandas
  - numpy
  - matplotlib
  - ipykernel
  - pip~=22.0
  - geopandas~=0.10
  - pydeck~=0.7
  - pyproj~=3.3.0
  - proj~=9.0
  - pyproj
  - requests~=2.27
  - h3pandas~=0.2
  - keplergl
  - rasterio~=1.2
  - pip:
      - git+https://github.com/pyalanysis/pyalanysis.git@develop
