---
name: Coverage
on: [push, pull_request]    # yamllint disable-line rule:truthy
jobs:
  Coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.9'
          architecture: x64
      - run: pip install nox==2022.1.7
      - run: pip install poetry==1.1.13
      - run: pip install nox-poetry==0.9.0
      - run: nox --sessions tests coverage
      - name: Send to codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
