---
name: Test
on: [push, pull_request]  # yamllint disable-line rule:truthy
jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        os: [ubuntu-18.04, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install nox==2022.1.7
      - run: pip install poetry==1.1.13
      - run: pip install nox-poetry==0.9.0
      # - run: poetry install && poetry run pytest
      - run: nox --sessions tests
